language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
virtual env:
    - system_site_packages: true
install:
    - python setup.py install
    - pip install codecov
    - pip install pytest-cov
script:
    - py.test --cov=cptools2 tests
after_success:
    - codecov
