"""
file_tools.py - File handling utilities for cptools2

This module extends cptools2 with capabilities for post-processing analysis
results generated by CellProfiler pipelines. The main functionality involves
automatically joining CSV output files based on patterns specified in the
configuration YAML file, with automatic metadata enrichment from LoadData files.

Key features:
- Automatically enriches output files with LoadData metadata before concatenation
- Combines output files across chunked jobs for each plate
- Supports multiple file patterns (e.g., "Image.csv", "Cells.csv")
- Creates organized output in a dedicated "joined_files" directory
- Provides detailed logging of the joining process
- Integrates with the cptools2 workflow configuration

These tools are especially useful in high-throughput image analysis workflows
where each plate's data might be spread across multiple output files due to
the chunking process. Rather than manually combining these files after analysis,
this module automates the process based on the original experiment structure.

Usage in YAML configuration:
```
join_files: ["Image.csv", "Cells.csv"]  # Join multiple file types
```
or
```
join_files: "Image.csv"  # Join a single file type
```

If no joining is required, simply omit the join_files parameter.
"""

import glob
import os

import pandas as pd
import polars as pl  # type: ignore[import-untyped]

from cptools2.colours import pretty_print, purple, red, yellow


def merge_loaddata_metadata(chunk_output_csv, loaddata_csv, output_path=None):
    """
    Merge LoadData metadata into CellProfiler output CSV using ImageNumber key.

    This function joins metadata from a LoadData CSV (containing Metadata_*
    columns) into a CellProfiler output CSV (Image.csv, Cells.csv, etc.)
    using ImageNumber as the join key. The join happens at the chunk level
    BEFORE concatenation to preserve metadata integrity.

    Parameters
    ----------
    chunk_output_csv : str
        Path to the CellProfiler output CSV file (e.g.,
        raw_data/plate_0/Image.csv)
    loaddata_csv : str
        Path to the corresponding LoadData CSV file (e.g.,
        loaddata/plate_0.csv)
    output_path : str, optional
        Path to write the enriched CSV. If None, overwrites chunk_output_csv
        in-place.

    Returns
    -------
    dict
        Dictionary containing:
        - 'success': bool - Whether merge completed successfully
        - 'output_file': str - Path to the enriched CSV
        - 'rows_before': int - Row count before merge
        - 'rows_after': int - Row count after merge
        - 'metadata_columns_added': list - Names of metadata columns added
        - 'null_metadata_count': int - Rows with null metadata (ImageNumber
          mismatch)

    Raises
    ------
    FileNotFoundError
        If input files don't exist
    ValueError
        If ImageNumber column not found in either file
    """
    result = {
        "success": False,
        "output_file": output_path or chunk_output_csv,
        "rows_before": 0,
        "rows_after": 0,
        "metadata_columns_added": [],
        "null_metadata_count": 0,
        "error": None,
    }

    try:
        # Validate files exist
        if not os.path.exists(chunk_output_csv):
            raise FileNotFoundError(f"Output CSV not found: {chunk_output_csv}")
        if not os.path.exists(loaddata_csv):
            raise FileNotFoundError(f"LoadData CSV not found: {loaddata_csv}")

        # Load CSVs with polars
        output_df = pl.read_csv(chunk_output_csv)
        loaddata_df = pl.read_csv(loaddata_csv)

        result["rows_before"] = len(output_df)

        # Validate ImageNumber column exists in both
        if "ImageNumber" not in output_df.columns:
            raise ValueError(
                f"ImageNumber column not found in output CSV: "
                f"{chunk_output_csv}"
            )
        if "ImageNumber" not in loaddata_df.columns:
            raise ValueError(
                f"ImageNumber column not found in LoadData CSV: "
                f"{loaddata_csv}"
            )

        # Extract only Metadata_* columns from LoadData (plus ImageNumber)
        metadata_cols = [
            col for col in loaddata_df.columns if col.startswith("Metadata_")
        ]
        cols_to_keep = ["ImageNumber"] + metadata_cols

        # Select and validate columns exist
        available_cols = [
            col for col in cols_to_keep if col in loaddata_df.columns
        ]
        if not available_cols:
            raise ValueError(
                f"No Metadata_* columns found in LoadData CSV: {loaddata_csv}"
            )

        loaddata_subset = loaddata_df.select(available_cols)
        result["metadata_columns_added"] = metadata_cols

        # Perform left join: keep all output rows, add metadata where available
        joined_df = output_df.join(
            loaddata_subset, on="ImageNumber", how="left"
        )

        # Validate join integrity: count null metadata (ImageNumber mismatch)
        if metadata_cols:
            # Count total nulls across all metadata columns
            null_count_df = joined_df.select(
                pl.col(metadata_cols).null_count()
            )
            null_count = (
                null_count_df.sum_horizontal()[0]
                if len(null_count_df) > 0
                else 0
            )
            result["null_metadata_count"] = null_count

            if null_count > 0:
                pretty_print(
                    "Warning: "
                    f"{null_count} rows have null metadata after join - "
                    "possible ImageNumber mismatch"
                )

        result["rows_after"] = len(joined_df)

        # Write enriched CSV
        output_file = output_path or chunk_output_csv
        joined_df.write_csv(output_file)
        result["output_file"] = output_file
        result["success"] = True

    except Exception as e:
        result["error"] = str(e)
        pretty_print(f"Error merging metadata: {red(str(e))}")

    return result


def _discover_chunks_for_plate(raw_data_location, plate_name):
    """
    Discover all chunk directories for a given plate.

    Parameters
    ----------
    raw_data_location : str
        Path to raw_data directory
    plate_name : str
        Plate name (e.g., 'plateName')

    Returns
    -------
    list
        Sorted list of chunk directory paths matching pattern plateName_*
    """
    chunks = []
    try:
        for item in os.listdir(raw_data_location):
            if item.startswith(f"{plate_name}_"):
                chunk_path = os.path.join(raw_data_location, item)
                if os.path.isdir(chunk_path):
                    chunks.append(chunk_path)
    except FileNotFoundError:
        pass
    return sorted(chunks)


def _discover_plates_from_raw_data(raw_data_location):
    """Discover plate names by examining directory structure in raw_data."""
    plate_names = set()
    try:
        # Look for directories like 'plateName_chunkNum' inside raw_data_location
        for item in os.listdir(raw_data_location):
            item_path = os.path.join(raw_data_location, item)
            if os.path.isdir(item_path) and "_" in item:
                # Split from right to avoid truncating plate names with underscores
                # Expected format: "<plate_name>_<job_or_chunk_id>"
                plate_name = item.rsplit("_", 1)[0]
                plate_names.add(plate_name)
    except FileNotFoundError:
        pretty_print(
            "Warning: Raw data location "
            f"{raw_data_location} not found during plate discovery."
        )
        return []
    if not plate_names:
        pretty_print(
            "Warning: No plate directories found in "
            f"{raw_data_location}. Cannot join files."
        )
    return sorted(list(plate_names))


def enrich_chunks_with_metadata(location, patterns=None):
    """
    Enrich all chunks with LoadData metadata before concatenation.

    This is the orchestration function that discovers all chunk/LoadData pairs
    and merges metadata into each chunk's output CSVs. This MUST happen before
    chunks are concatenated to preserve metadata integrity (ImageNumber is
    sequential per chunk).

    Parameters
    ----------
    location : str
        Base location directory containing 'loaddata/' and 'raw_data/'
        subdirectories
    patterns : list, optional
        List of CSV filename patterns to enrich (e.g.,
        ['Image.csv', 'Cells.csv']). If None, discovers all CSV files
        in chunks.

    Returns
    -------
    dict
        Dictionary with enrichment results:
        - 'total_chunks_processed': int
        - 'total_files_enriched': int
        - 'total_rows_enriched': int
        - 'chunks': dict - Per-chunk details
        - 'errors': list - Any errors encountered
    """
    results = {
        "total_chunks_processed": 0,
        "total_files_enriched": 0,
        "total_rows_enriched": 0,
        "chunks": {},
        "errors": [],
    }

    raw_data_location = os.path.join(location, "raw_data")
    loaddata_location = os.path.join(location, "loaddata")

    # Validate directories exist
    if not os.path.exists(raw_data_location):
        pretty_print(
            f"Raw data directory not found: {red(raw_data_location)}"
        )
        results["errors"].append(
            f"Raw data directory not found: {raw_data_location}"
        )
        return results

    if not os.path.exists(loaddata_location):
        pretty_print("LoadData directory not found - skipping metadata enrichment")
        return results

    pretty_print("PHASE 1: Starting metadata enrichment...")
    pretty_print(f"Scanning for chunks in: {yellow(raw_data_location)}")

    # Discover all plates
    plate_names = _discover_plates_from_raw_data(raw_data_location)
    if not plate_names:
        pretty_print("No plates found in raw_data directory.")
        return results

    # Process each plate's chunks
    for plate_name in plate_names:
        pretty_print(f"Processing plate: {purple(plate_name)}")

        # Discover chunks for this plate
        chunks = _discover_chunks_for_plate(raw_data_location, plate_name)
        if not chunks:
            pretty_print(f"\tNo chunks found for plate {purple(plate_name)}")
            continue

        results["chunks"][plate_name] = []

        # Process each chunk
        for chunk_path in chunks:
            chunk_name = os.path.basename(chunk_path)

            # Find corresponding LoadData CSV
            loaddata_csv = os.path.join(
                loaddata_location, f"{chunk_name}.csv"
            )

            if not os.path.exists(loaddata_csv):
                msg = f"\t\tNo LoadData file found for {chunk_name}"
                pretty_print(msg)
                results["errors"].append(msg)
                continue

            pretty_print(f"\t{chunk_name}")

            # Discover CSV files in this chunk
            chunk_csvs = []
            if patterns:
                # If patterns specified, only look for those
                for pattern in patterns:
                    matching = glob.glob(
                        os.path.join(chunk_path, pattern)
                    )
                    chunk_csvs.extend(matching)
            else:
                # Otherwise, find all CSV files
                chunk_csvs = glob.glob(os.path.join(chunk_path, "*.csv"))

            if not chunk_csvs:
                pretty_print("\t\tNo CSV files found in chunk")
                continue

            # Enrich each CSV file in the chunk
            chunk_results = []
            for csv_file in sorted(chunk_csvs):
                csv_name = os.path.basename(csv_file)

                # Merge metadata into this CSV (overwrite in-place)
                merge_result = merge_loaddata_metadata(
                    csv_file, loaddata_csv
                )

                if merge_result["success"]:
                    pretty_print(
                        f"\t\t{yellow(csv_name)}: "
                        f"{purple(merge_result['rows_after'])} rows, "
                        f"{purple(len(merge_result['metadata_columns_added']))}"
                        " metadata columns"
                    )
                    results["total_files_enriched"] += 1
                    results["total_rows_enriched"] += merge_result[
                        "rows_after"
                    ]
                    chunk_results.append(merge_result)
                else:
                    msg = (
                        f"\t\tFailed to enrich {csv_name}: "
                        f"{merge_result['error']}"
                    )
                    pretty_print(msg)
                    results["errors"].append(msg)

            if chunk_results:
                results["chunks"][plate_name].append(
                    {
                        "chunk_name": chunk_name,
                        "files_enriched": len(chunk_results),
                        "details": chunk_results,
                    }
                )
                results["total_chunks_processed"] += 1

    pretty_print("Metadata enrichment complete!")
    pretty_print(
        f"Enriched {yellow(results['total_files_enriched'])} files across "
        f"{yellow(results['total_chunks_processed'])} chunks"
    )

    return results


def join_plate_files(
    plate_store,
    raw_data_location,
    patterns=None,
    batch_id=None,
    enrich_metadata=True,
):
    """
    Join result files for each plate based on specified patterns.

    IMPORTANT: Metadata enrichment happens BEFORE concatenation. This is
    critical because ImageNumber is sequential within each chunk (1-96,
    1-96, ...) and resets per chunk. If we concatenate first, ImageNumber
    loses meaning. By enriching each chunk individually before concatenation,
    we preserve metadata integrity.

    If plate_store is None, attempts to discover plate names from the
    directory structure within raw_data_location.

    Parameters
    ----------
    plate_store : dict or None
        Dictionary of plates from Job.plate_store, or None to discover plates.
    raw_data_location : string
        Path to where raw data (chunked directories like 'plateName_chunkNum')
        is stored.
    patterns : list or None
        List of file patterns to join (e.g., ["Image.csv", "Cells.csv"])
        If None, no files will be joined.
    batch_id : int or None
        Optional identifier for the batch, used to create a unique output
        directory.
    enrich_metadata : bool (default=True)
        Whether to enrich chunks with LoadData metadata before concatenation.

    Returns
    -------
    dict or None
        Dictionary with joined file information, or None if no patterns.
    """
    if not patterns:
        pretty_print("No file joining patterns specified. Skipping file joining.")
        return None

    # PHASE 1: ENRICH chunks with metadata BEFORE concatenation
    if enrich_metadata:
        location = os.path.dirname(raw_data_location)
        enrich_results = enrich_chunks_with_metadata(location, patterns)

        if enrich_results["errors"]:
            pretty_print(
                "Enrichment completed with "
                f"{len(enrich_results['errors'])} warnings/errors"
            )
        else:
            pretty_print("Enrichment successful!")

    # PHASE 2: Concatenate enriched chunks
    pretty_print("PHASE 2: Concatenating enriched chunks...")
    pretty_print(
        "Joining files with patterns: {}".format(
            ", ".join([yellow(pattern) for pattern in patterns])
        )
    )

    results = {}

    # Determine plate names: use plate_store if provided, otherwise discover
    if plate_store:
        plate_names = sorted(plate_store.keys())
        pretty_print(
            f"Using plate names from provided plate_store: "
            f"{len(plate_names)}"
        )
    else:
        pretty_print(
            f"No plate_store provided. Discovering plates from: "
            f"{raw_data_location}"
        )
        plate_names = _discover_plates_from_raw_data(raw_data_location)
        if not plate_names:
            return None  # Stop if no plates were found
        pretty_print(
            f"Discovered plate names: {', '.join(purple(p) for p in plate_names)}"
        )

    for pattern in patterns:
        pretty_print("Processing pattern: {}".format(yellow(pattern)))

        for plate_name in plate_names:
            pretty_print(
                "\tProcessing plate: {}".format(purple(plate_name))
            )

            # Find all files matching the pattern for this plate
            search_pattern = os.path.join(
                raw_data_location, f"{plate_name}_*", pattern
            )
            matched_files = glob.glob(search_pattern)

            if not matched_files:
                pretty_print(
                    f"\tNo files found for plate {purple(plate_name)} "
                    f"with pattern {yellow(pattern)}"
                )
                continue

            try:
                # Combine enriched files
                combined_csv = pd.concat(
                    [
                        pd.read_csv(f, low_memory=False)
                        for f in matched_files
                    ]
                )

                # Determine output directory (batch-specific if batch_id provided)
                parent_dir = os.path.dirname(raw_data_location)
                if batch_id is not None:
                    output_dir_name = f"joined_files_batch_{batch_id}"
                else:
                    output_dir_name = "joined_files"

                output_dir = os.path.join(parent_dir, output_dir_name)
                os.makedirs(output_dir, exist_ok=True)
                output_file = os.path.join(
                    output_dir, f"{plate_name}_{pattern}"
                )

                combined_csv.to_csv(
                    output_file, index=False, encoding="utf-8-sig"
                )

                # Store output info
                if plate_name not in results:
                    results[plate_name] = {}
                results[plate_name][pattern] = {
                    "output_file": output_file,
                    "rows": len(combined_csv),
                    "files_combined": len(matched_files),
                    "metadata_enriched": enrich_metadata,
                }

                pretty_print(
                    f"\tCreated {yellow(output_file)} with "
                    f"{purple(len(combined_csv))} rows from "
                    f"{purple(len(matched_files))} files"
                )
            except Exception as e:
                pretty_print(
                    f"\tError processing pattern {yellow(pattern)} "
                    f"for plate {purple(plate_name)}: {str(e)}"
                )

    return results
