"""
Generate eddie submission scripts for the
staging, analysis and destaging jobs
"""

from __future__ import print_function
import os
import sys
import textwrap
from datetime import datetime
import shutil
import subprocess
import re
import getpass

try:
    from scissorhands import script_generator
except ImportError:
    print("Error: scissorhands package not found. Please install it with:")
    print("pip install 'git+https://github.com/carragherlab/scissorhands.git@master#egg=scissorhands'")
    sys.exit(1)

from cptools2 import utils
from cptools2 import colours
from cptools2.colours import pretty_print, green


def make_command_paths(commands_location):
    """
    create the paths to the commands
    """
    names = ["staging", "cp_commands", "destaging"]
    return {name: os.path.join(commands_location, name+".txt") for name in names}


def load_module_text(is_cellprofiler=False):
    """returns load module commands, optionally activating cellprofiler env"""
    script_text = textwrap.dedent(
        """
        module load anaconda/2024.02
        """
    )
    if is_cellprofiler:
        script_text += textwrap.dedent(
            """
            conda activate cellprofiler
            """
        )
    return script_text


def make_logfile_text(logfile_location, job_file, n_tasks):
    text = """
    # get the exit code from the cellprofiler job
    RETURN_VAL=$?

    if [[ $RETURN_VAL == 0 ]]; then
        RETURN_STATUS="Finished"
    else
        RETURN_STATUS="Failed with error code: $RETURN_VAL"
    fi

    LOG_FILE_LOC={logfile_location}/{job_file}.log
    echo "`date +"%Y-%m-%d %H:%M"`  "$JOB_ID"  "$SGE_TASK_ID"  "$RETURN_STATUS"" >> "$LOG_FILE_LOC"
    """.format(logfile_location=logfile_location,
               job_file=job_file)
    return textwrap.dedent(text)


class SafePathScript(script_generator.SGEScript):
    """
    Overwrites the __add__ method of the script_generator.SGEScript
    class to enable adding new lines which contain paths, without
    them being converted to absolute paths by the script_generator
    """
    def __add__(self, new_line):
        self.script += new_line
        return self


def create_master_submit_script(commands_location, logfile_location, batches, config):
    """
    Create master script that generates and submits all SGE jobs with proper dependencies.
    Always uses batch workflow for consistency.
    
    Parameters:
    -----------
    commands_location : str
        Directory containing command files
    logfile_location : str
        Directory for SGE logs
    batches : list
        List of batch dictionaries from batch planning
    config : namedtuple
        Configuration needed for join/transfer scripts
        
    Returns:
    --------
    str : Path to created master submission script
    """
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    
    # This call now returns all scripts, including join/transfer
    all_scripts = make_qsub_scripts(config, commands_location, logfile_location, batches)

    script_content = _create_chained_submission_content(all_scripts)
    script_name = f"{timestamp}_SUBMIT_BATCH_MASTER.sh"
    
    # Write master script
    script_path = os.path.join(commands_location, script_name)
    with open(script_path, 'w') as f:
        f.write(script_content)
    utils.make_executable(script_path)
    
    pretty_print(colours.green("[cptools2] master script created:"))
    pretty_print(f"\t {colours.yellow(script_name)}")
    
    return script_path


def _create_chained_submission_content(all_scripts):
    """
    Generate a lean master script that submits jobs trusting their built-in dependencies.
    This script is non-interactive but provides a final confirmation message.
    """
    lines = [
        "#!/bin/sh",
        "# Master submission script generated by cptools2.",
        "# This script submits all jobs, relying on the dependencies",
        "# embedded within each individual job script.",
        "",
        "# NOTE: run this as a shell script, NOT a submission script",
        "# so either call `./name_of_script` or `bash name_of_script`",
    ]

    for script_path in all_scripts:
        lines.append(f"qsub \"{script_path}\"")

    lines.append("\necho \"All batch jobs submitted successfully.\"")
    
    return '\n'.join(lines)





def get_available_scratch_space(path):
    """Returns available space in bytes on the drive of the given path."""
    check_path = path
    while not os.path.exists(check_path):
        check_path = os.path.dirname(check_path)
        if not check_path or check_path == os.path.dirname(check_path):
            # we've reached the root and it doesn't exist, something is very wrong
            raise FileNotFoundError(f"Could not find existing path from {path} to check disk space.")
    total, used, free = shutil.disk_usage(check_path)
    return free


def get_user_scratch_quota(user=None):
    """
    Returns available scratch space for the user on Eddie by checking /exports/eddie/scratch/$USER.
    Uses 75% of the free space for batch planning. Falls back to 2TB if detection fails.
    """
    try:
        if user is None:
            user = getpass.getuser()
        scratch_dir = f"/exports/eddie/scratch/{user}"
        
        print(f"[cptools2] DEBUG: Checking scratch directory: {scratch_dir}")
        
        if not os.path.exists(scratch_dir):
            raise FileNotFoundError(f"Scratch directory not found: {scratch_dir}")
        
        # Eddie-specific quota-aware approach
        # Known quota limit (update this if your quota changes)
        quota_total_gb = 2048  # 2TB quota on Eddie scratch
        
        # Calculate current usage using du command (faster and more accurate)
        try:
            import subprocess
            result = subprocess.run(['du', '-sb', scratch_dir], 
                                  capture_output=True, text=True, timeout=30)
            if result.returncode == 0:
                used_bytes = int(result.stdout.split()[0])
                used_gb = used_bytes / (1024**3)
                available_gb = max(0, quota_total_gb - used_gb)
                available_75pct_bytes = int(available_gb * 0.75 * (1024**3))
                
                print(f"[cptools2] DEBUG: Quota: {quota_total_gb}GB, Used: {used_gb:.1f}GB, Available: {available_gb:.1f}GB")
                print(f"[cptools2] Using quota-aware calculation: {available_75pct_bytes/(1024**3):.1f}GB (75% of {available_gb:.1f}GB available)")
                return available_75pct_bytes
        except Exception as du_error:
            print(f"[cptools2] DEBUG: du command failed: {du_error}")
        
        # Fallback: Conservative estimate (75% of total quota)
        fallback_bytes = int(quota_total_gb * 0.75 * (1024**3))
        print(f"[cptools2] Using conservative fallback: {fallback_bytes/(1024**3):.1f}GB (75% of {quota_total_gb}GB quota)")
        return fallback_bytes
        
    except Exception as e:
        print(f"[cptools2] Warning: Failed to calculate scratch space: {e}. Falling back to 2TB.")
    return 2 * 1024**4  # 2TB fallback


def make_join_files_script(config, commands_location, logfile_location, job_name, timestamp, dependency_job_name=None, plates_to_join=None, batch_id=None):
    """
    Create a qsub submission script for joining result files based on patterns.
    """
    if not hasattr(config, 'join_files_patterns') or not config.join_files_patterns:
        return None

    patterns = config.join_files_patterns
    location = config.create_command_args["location"]

    patterns_str = ", ".join([colours.yellow(p) for p in patterns])
    
    # Base command
    join_command = f'cptools2 join --location "{location}" --patterns {" ".join(patterns)}'
    
    # Add batch ID if provided
    if batch_id is not None:
        join_command += f" --batch-id {batch_id}"

    # Add specific plates if provided
    if plates_to_join:
        pretty_print(f"  -> Generating join script for plates: {', '.join(plates_to_join)}")
        join_command += f" --plates {' '.join(plates_to_join)}"
    else:
        pretty_print(f"  -> Generating join script for all plates with patterns: {patterns_str}")

    join_script = SafePathScript(
        name=job_name,
        memory="2G",
        tasks=1,
        output=os.path.join(logfile_location, "join")
    )

    if dependency_job_name:
        join_script += f"#$ -hold_jid {dependency_job_name}\n"

    join_script += ". /etc/profile.d/modules.sh\n"
    join_script += load_module_text(is_cellprofiler=False)
    join_script += "export PATH=\"$HOME/.local/bin:$PATH\"\n"
    join_script += join_command + "\n"

    join_loc = os.path.join(commands_location, f"{timestamp}_{job_name}.sh")
    join_script.save(join_loc)
    utils.make_executable(join_loc)

    return join_loc


def make_datastore_transfer_script(config, commands_location, logfile_location, job_name, timestamp, eddie_source_dir, dependency_job_name=None, batch_id=None):
    """
    Create a script to transfer joined data to DataStore.
    """
    datastore_dest = config.data_destination_path
    if not datastore_dest:
        return None

    # Modify source directory to be batch-specific if a batch_id is provided
    if batch_id is not None:
        joined_dir_name = f"joined_files_batch_{batch_id}"
    else:
        joined_dir_name = "joined_files"
    specific_eddie_source_for_transfer = os.path.join(eddie_source_dir, joined_dir_name).replace("\\", "/")
    pretty_print(f"  -> Generating datastore transfer script to: {colours.yellow(datastore_dest)}")

    transfer_script = SafePathScript(
        name=job_name,
        memory="1G",
        tasks=1,
        output=os.path.join(logfile_location, "transfer")
    )
    
    transfer_script += "#$ -q staging\n"
    if dependency_job_name:
        transfer_script += f"#$ -hold_jid {dependency_job_name}\n"
    
    transfer_script += "#$ -m e\n"
    transfer_script += "#$ -M $USER@ed.ac.uk\n"
    
    transfer_script += f"EDDIE_SOURCE_DIR=\"{specific_eddie_source_for_transfer}\"\n"
    transfer_script += f"DATASTORE_DEST_DIR=\"{datastore_dest}\"\n"
    
    rsync_log_file = os.path.join(logfile_location, f"transfer_to_datastore_{job_name}.log")
    transfer_script += f"RSYNC_LOG_FILE=\"{rsync_log_file}\"\n"
    
    transfer_script += "echo \"Starting data transfer at $(date)\" > \"$RSYNC_LOG_FILE\"\n"
    transfer_script += "mkdir -p \"$DATASTORE_DEST_DIR\"\n"
    transfer_script += "rsync -av --stats \"$EDDIE_SOURCE_DIR/\" \"$DATASTORE_DEST_DIR/\" >> \"$RSYNC_LOG_FILE\" 2>&1\n"
    
    transfer_loc = os.path.join(commands_location, f"{timestamp}_{job_name}.sh")
    transfer_script.save(transfer_loc)
    utils.make_executable(transfer_loc)
    
    return transfer_loc


def generate_job_names(job_hex):
    """Generate consistent job names for dependency management"""
    return {
        'staging': f"staging_{job_hex}",
        'analysis': f"analysis_{job_hex}",
        'destaging': f"destaging_{job_hex}",
        'join': f"join_{job_hex}",
        'transfer': f"transfer_{job_hex}"
    }


def make_qsub_scripts(config, commands_location, logfile_location, batches):
    """Create SGE submission scripts with sequential batch dependencies."""
    pretty_print(f"[cptools2] creating SGE scripts for {len(batches)} sequential batches...")
    all_script_paths = []
    previous_destaging_job = None  # No dependency for first batch
    for batch in batches:
        batch_scripts, destaging_job_name = _create_batch_scripts(
            batch, config, commands_location, logfile_location,
            previous_batch_destaging_job=previous_destaging_job
        )
        all_script_paths.extend(batch_scripts)
        previous_destaging_job = destaging_job_name  # Chain for next batch
    pretty_print(f"[cptools2] created {len(all_script_paths)} scripts with sequential dependencies")
    
    return all_script_paths


def _create_batch_scripts(batch, config, commands_location, logfile_location, previous_batch_destaging_job=None):
    """
    Create staging → analysis → destaging → join → transfer chain for a single batch.
    previous_batch_destaging_job: job name of previous batch's destaging job (for sequential processing)
    Returns (scripts_created, this_batch_destaging_job_name)
    """
    from scissorhands import script_generator
    batch_id = batch['batch_id']
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    job_hex = f"b{batch_id}_{timestamp[-6:]}"
    job_names = generate_job_names(job_hex)
    scripts_created = []

    # 1. Staging (waits for previous batch's destaging)
    staging_script_path = _create_staging_script(
        batch_id, commands_location, logfile_location, job_hex,
        dependency_job_name=previous_batch_destaging_job
    )
    scripts_created.append(staging_script_path)

    # 2. Analysis (waits for this batch's staging)
    analysis_script_path = _create_analysis_script(
        batch_id, commands_location, logfile_location, job_hex,
        dependency_job_name=job_names['staging']
    )
    scripts_created.append(analysis_script_path)

    # 3. Destaging (waits for this batch's analysis)
    destaging_script_path = _create_destaging_script(
        batch_id, commands_location, logfile_location, job_hex,
        dependency_job_name=job_names['analysis']
    )
    scripts_created.append(destaging_script_path)

    # 4. Join (optional, waits for destaging)
    join_script_path = None
    if hasattr(config, 'join_files_patterns') and config.join_files_patterns:
        join_script_path = make_join_files_script(
            config, commands_location, logfile_location, job_names['join'], timestamp,
            dependency_job_name=job_names['destaging'],
            plates_to_join=batch['plates'],
            batch_id=batch_id
        )
        if join_script_path:
            scripts_created.append(join_script_path)

    # 5. Transfer (optional, waits for join OR destaging)
    transfer_dependency = job_names['join'] if join_script_path else job_names['destaging']
    if hasattr(config, 'data_destination_path') and config.data_destination_path:
        transfer_script_path = make_datastore_transfer_script(
            config, commands_location, logfile_location, job_names['transfer'], timestamp,
            eddie_source_dir=config.create_command_args["location"],
            dependency_job_name=transfer_dependency,
            batch_id=batch_id
        )
        if transfer_script_path:
            scripts_created.append(transfer_script_path)

    return scripts_created, job_names['destaging']  # Return destaging job name for next batch


def _create_staging_script(batch_id, commands_location, logfile_location, job_hex, dependency_job_name=None):
    """
    Create SGE array job script for staging (rsync) operations.
    If dependency_job_name is provided, use hold_jid_ad for robust sequential dependency.
    """
    staging_file = os.path.join(commands_location, f"staging_batch_{batch_id}.txt")
    if not os.path.exists(staging_file):
        raise FileNotFoundError(f"Staging command file not found: {staging_file}")
    n_tasks = utils.count_lines_in_file(staging_file)
    staging_script = SafePathScript(
        name=f"staging_{job_hex}",
        memory="1G",
        tasks=n_tasks,
        output=os.path.join(logfile_location, "staging")
    )
    # Add dependency if provided
    if dependency_job_name:
        staging_script += f"#$ -hold_jid {dependency_job_name}\n"
    staging_script += "#$ -q staging\n"
    staging_script += f'COMMAND=$(sed -n "${{SGE_TASK_ID}}p" "{staging_file}")\n'
    staging_script += 'echo "$COMMAND" | base64 -d | /bin/bash\n'
    script_path = os.path.join(commands_location, f"staging_{job_hex}.sh")
    staging_script.save(script_path)
    utils.make_executable(script_path)
    return script_path


def _create_analysis_script(batch_id, commands_location, logfile_location, job_hex, dependency_job_name=None):
    """
    Create SGE array job script for CellProfiler analysis.
    
    Parameters:
    -----------
    batch_id : int
        Batch identifier
    commands_location : str
        Directory containing command files
    logfile_location : str
        Directory for SGE logs
    job_hex : str
        Unique job identifier
    dependency_job_name : str
        Name of job this depends on (staging job)
        
    Returns:
    --------
    str : Path to created analysis script
    """
    from scissorhands import script_generator
    
    # Reference the batch-specific analysis command file
    analysis_file = os.path.join(commands_location, f"cp_commands_batch_{batch_id}.txt")
    
    if not os.path.exists(analysis_file):
        raise FileNotFoundError(f"Analysis command file not found: {analysis_file}")
    
    # Count tasks
    n_tasks = utils.count_lines_in_file(analysis_file)
    
    # Create analysis script (use script_generator.AnalysisScript for proper CellProfiler setup)
    analysis_script = script_generator.AnalysisScript(
        name=f"analysis_{job_hex}",
        tasks=n_tasks,
        hold_jid_ad=dependency_job_name,
        pe="sharedmem 1",
        memory="24G",
        output=os.path.join(logfile_location, "analysis")
    )
    
    # Add module loading
    analysis_script += load_module_text(is_cellprofiler=True)
    
    # Add command execution (with base64 decoding)
    analysis_script += f'COMMAND=$(sed -n "${{SGE_TASK_ID}}p" "{analysis_file}")\n'
    analysis_script += 'echo "$COMMAND" | base64 -d | /bin/bash\n'
    
    # Save script
    script_path = os.path.join(commands_location, f"analysis_{job_hex}.sh")
    analysis_script.save(script_path)
    utils.make_executable(script_path)
    
    return script_path


def _create_destaging_script(batch_id, commands_location, logfile_location, job_hex, dependency_job_name=None):
    """
    Create SGE array job script for destaging (cleanup) operations.
    
    Parameters:
    -----------
    batch_id : int
        Batch identifier
    commands_location : str
        Directory containing command files
    logfile_location : str
        Directory for SGE logs
    job_hex : str
        Unique job identifier
    dependency_job_name : str
        Name of job this depends on (analysis job)
        
    Returns:
    --------
    str : Path to created destaging script
    """
    # Reference the batch-specific destaging command file
    destaging_file = os.path.join(commands_location, f"destaging_batch_{batch_id}.txt")
    
    if not os.path.exists(destaging_file):
        raise FileNotFoundError(f"Destaging command file not found: {destaging_file}")
    
    # Count tasks
    n_tasks = utils.count_lines_in_file(destaging_file)
    
    # Create SGE script
    destaging_script = SafePathScript(
        name=f"destaging_{job_hex}",
        memory="1G",
        tasks=n_tasks,
        output=os.path.join(logfile_location, "destaging")
    )
    
    # Add dependency
    if dependency_job_name:
        destaging_script += f"#$ -hold_jid {dependency_job_name}\n"
    
    # Add command execution logic
    destaging_script += f'COMMAND=$(sed -n "${{SGE_TASK_ID}}p" "{destaging_file}")\n'
    destaging_script += 'echo "$COMMAND" | base64 -d | /bin/bash\n'
    
    # Save script
    script_path = os.path.join(commands_location, f"destaging_{job_hex}.sh")
    destaging_script.save(script_path)
    utils.make_executable(script_path)
    
    return script_path










