"""Launch one Eddie DeepProfiler scalability route from a matrix JSON file."""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
from pathlib import Path


def _load_route(matrix_path: Path, route_name: str) -> dict[str, object]:
    matrix = json.loads(matrix_path.read_text(encoding="utf-8"))
    for route in matrix:
        if route.get("name") == route_name:
            return route
    choices = ", ".join(str(route.get("name")) for route in matrix)
    raise SystemExit(f"Unknown route {route_name!r}; available routes: {choices}")


def write_launch_script(route: dict[str, object], *, resume: bool = False) -> Path:
    run_root = Path(str(route["run_root"]))
    run_root.mkdir(parents=True, exist_ok=True)
    launch_path = run_root / "launch.sh"
    status_path = run_root / "status.txt"
    remote_command = str(route["remote_command"])
    if resume and "--resume" not in remote_command:
        remote_command = f"{remote_command} --resume"
    launch_path.write_text(
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "set +e",
                f"bash -lc {shlex.quote(remote_command)}",
                "rc=$?",
                f"echo \"$rc\" > {shlex.quote(str(status_path))}",
                "exit $rc",
                "",
            ]
        ),
        encoding="utf-8",
    )
    launch_path.chmod(0o755)
    return launch_path


def launch_route(route: dict[str, object], *, resume: bool = False) -> int:
    run_root = Path(str(route["run_root"]))
    launch_path = write_launch_script(route, resume=resume)
    status_path = run_root / "status.txt"
    log_path = run_root / "launcher.log"
    status_path.unlink(missing_ok=True)

    log_handle = log_path.open("ab")
    process = subprocess.Popen(
        ["bash", str(launch_path)],
        cwd=run_root,
        stdout=log_handle,
        stderr=subprocess.STDOUT,
        start_new_session=True,
    )
    log_handle.close()
    print(f"PID={process.pid}")
    print(f"ROUTE={route['name']}")
    print(f"RUN_ROOT={run_root}")
    print(f"LOG={log_path}")
    print(f"STATUS={status_path}")
    print(f"RESUME={str(resume).lower()}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Launch one DeepProfiler scalability route on Eddie."
    )
    parser.add_argument("matrix", type=Path, help="matrix JSON generated by the runner")
    parser.add_argument("route", help="route name to launch")
    parser.add_argument(
        "--resume",
        action="store_true",
        help="append --resume to the cptools2 pipeline command",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    route = _load_route(args.matrix, args.route)
    return launch_route(route, resume=args.resume)


if __name__ == "__main__":
    raise SystemExit(main())
